# SPDX-License-Identifier: GPL-3.0-only
if(NOT EXISTS "${WEB_DIST}/index.html")
    message(FATAL_ERROR "Awake frontend build did not produce index.html")
endif()
file(COPY_FILE "${WEBCHANNEL_JS}" "${WEB_DIST}/qwebchannel.js")
file(GLOB_RECURSE WEB_FILES LIST_DIRECTORIES false RELATIVE "${WEB_DIST}" "${WEB_DIST}/*")
list(SORT WEB_FILES)
set(QRC_CONTENT "<RCC><qresource prefix=\"/awake-web\">\n")
foreach(WEB_FILE IN LISTS WEB_FILES)
    set(WEB_PATH "${WEB_DIST}/${WEB_FILE}")
    foreach(XML_VAR WEB_FILE WEB_PATH)
        string(REPLACE "&" "&amp;" ${XML_VAR} "${${XML_VAR}}")
        string(REPLACE "\"" "&quot;" ${XML_VAR} "${${XML_VAR}}")
        string(REPLACE "<" "&lt;" ${XML_VAR} "${${XML_VAR}}")
        string(REPLACE ">" "&gt;" ${XML_VAR} "${${XML_VAR}}")
    endforeach()
    string(APPEND QRC_CONTENT "  <file alias=\"${WEB_FILE}\">${WEB_PATH}</file>\n")
endforeach()
string(APPEND QRC_CONTENT "</qresource></RCC>\n")
file(WRITE "${WEB_QRC}" "${QRC_CONTENT}")
